apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: osixia/openldap:latest
        ports:
        - containerPort: 389
        - containerPort: 636
        env:
        - name: LDAP_ORGANISATION
          value: "My Company"
        - name: LDAP_DOMAIN
          value: "mycompany.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "ldapadmin"
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  selector:
    app: ldap
  ports:
    - name: ldap-port
      protocol: TCP
      port: 389
      targetPort: 389
    - name: ldaps-port
      protocol: TCP
      port: 636
      targetPort: 636
  type: ClusterIP
